### ISSUE TITLE
Option to disable sorting of output?

### ISSUE THREAD

**Issue by davuses** [johnbumgarner/wordhoard#27]
I've notices that the output of synonyms are sorted alphabetically, which defeats the purpose of sorting by relevance? Is there an option to disable this?

**Comment by johnbumgarner** [comment]
I created this program in a vacuum with very little feedback from the masses that use it I’ve never given any thought to having this as a filter, but I will look into it as an enhancement to the application. I do not have a timeframe to add this to the current module. I’m going to close this issue because I’ve put this in the queue to add to the module. if I have difficulties, adding this, I will let you know.

**Comment by johnbumgarner** [comment]
@davuses  can you provide me examples on how this would work when parsing data from more than one source?

**Comment by davuses** [comment]
> @davuses can you provide me examples on how this would work when parsing data from more than one source?

In my use case I only need to fetch data from one source (Merriam Webster), so it makes no sense to sort the output alphabetically.
